### ISSUE TITLE
Some keyword are missing

### ISSUE THREAD

**Issue by jolkdarr** [AndiDog/atom-slice#1]
Some keywords shall be added in the grammar file:
- `extends`
- `implements`
- `local`
- `optional`
- `out`
- `short`
- `#endif`

Some keywords should be added in the grammar file:
- `false` and `true`
- `Object` and `LocalObject`

List of keywords: https://doc.zeroc.com/display/Ice36/Slice+Keywords

**Comment by AndiDog** [comment]
Fixed in 0.0.4
