### ISSUE TITLE
Scope operator should be highlighted

### ISSUE THREAD

**Issue by jolkdarr** [AndiDog/atom-slice#3]
Scope operator `::` should be highlighted (even as keyword).

**Comment by AndiDog** [comment]
Do you have an example? I can only think of struct members, for instance, which are also not highlighted for C++. Hence I wouldn't change it. However one could give it some CSS class so you could customize.

**Comment by jolkdarr** [comment]
The `::` in Slice has same function that `::` in IDL (Corba) or C++. It specifies scopes or namespaces (defined by means of modules in ICE files).
I agree with you: highlighting is not absolutely necessary. I suggest that because I find it useful in Slice specifications.
In C++, the scope operator is massively used (generally with `std` namespace) and highlighting is not necessarily advisable. 
Your solution (CSS style) is simple and let everyone choose the final look of ICE files in Atom.

**Comment by AndiDog** [comment]
With v0.0.5 (d3c6306d8509c36f9791b1d60f830d522ea27e45), you can style this operator finally, e.g.

```less
.syntax--slice.syntax--namespace.syntax--access {
  color: red;
}
```
